const worldCupChampions = {
  '巴西': 5,
  '德国': 4,
  '意大利': 4,
  '阿根廷': 3,
  '法国': 2,
  '乌拉圭': 2,
  '英格兰': 1,
  '西班牙': 1
};

const countryContinent = {
  '阿根廷': '南美洲',
  '巴西': '南美洲',
  '乌拉圭': '南美洲',
  '哥伦比亚': '南美洲',
  '智利': '南美洲',
  '秘鲁': '南美洲',
  '厄瓜多尔': '南美洲',
  '巴拉圭': '南美洲',
  '委内瑞拉': '南美洲',
  '玻利维亚': '南美洲',
  '法国': '欧洲',
  '德国': '欧洲',
  '意大利': '欧洲',
  '西班牙': '欧洲',
  '英格兰': '欧洲',
  '葡萄牙': '欧洲',
  '荷兰': '欧洲',
  '比利时': '欧洲',
  '克罗地亚': '欧洲',
  '波兰': '欧洲',
  '挪威': '欧洲',
  '瑞典': '欧洲',
  '丹麦': '欧洲',
  '瑞士': '欧洲',
  '塞尔维亚': '欧洲',
  '乌克兰': '欧洲',
  '奥地利': '欧洲',
  '苏格兰': '欧洲',
  '威尔士': '欧洲',
  '捷克': '欧洲',
  '匈牙利': '欧洲',
  '罗马尼亚': '欧洲',
  '土耳其': '欧洲',
  '希腊': '欧洲',
  '斯洛伐克': '欧洲',
  '斯洛文尼亚': '欧洲',
  '保加利亚': '欧洲',
  '爱尔兰': '欧洲',
  '芬兰': '欧洲',
  '冰岛': '欧洲',
  '波黑': '欧洲',
  '阿尔巴尼亚': '欧洲',
  '北马其顿': '欧洲',
  '黑山': '欧洲',
  '科索沃': '欧洲',
  '格鲁吉亚': '欧洲',
  '俄罗斯': '欧洲',
  '埃及': '非洲',
  '塞内加尔': '非洲',
  '尼日利亚': '非洲',
  '摩洛哥': '非洲',
  '喀麦隆': '非洲',
  '加纳': '非洲',
  '科特迪瓦': '非洲',
  '阿尔及利亚': '非洲',
  '突尼斯': '非洲',
  '马里': '非洲',
  '南非': '非洲',
  '几内亚': '非洲',
  '布基纳法索': '非洲',
  '刚果民主共和国': '非洲',
  '加蓬': '非洲',
  '多哥': '非洲',
  '韩国': '亚洲',
  '日本': '亚洲',
  '伊朗': '亚洲',
  '沙特阿拉伯': '亚洲',
  '澳大利亚': '亚洲',
  '卡塔尔': '亚洲',
  '阿联酋': '亚洲',
  '伊拉克': '亚洲',
  '乌兹别克斯坦': '亚洲',
  '中国': '亚洲',
  '墨西哥': '北美洲',
  '美国': '北美洲',
  '加拿大': '北美洲',
  '哥斯达黎加': '北美洲',
  '牙买加': '北美洲',
  '巴拿马': '北美洲',
  '洪都拉斯': '北美洲',
  '海地': '北美洲',
  '新西兰': '大洋洲'
};

function getWorldCupWins(country) {
  return worldCupChampions[country] || 0;
}

function getContinent(country) {
  return countryContinent[country] || '未知';
}

function calculateAge(birthday) {
  const birth = new Date(birthday);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const monthDiff = today.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
    age--;
  }
  return age;
}

function createStar(id, name, nameEn, country, age, worldCupWins) {
  return {
    id,
    name,
    nameEn,
    country,
    worldCupWins: worldCupWins || 0,
    continent: getContinent(country),
    age,
    source: 'local'
  };
}

const stars = [
  createStar(1, '梅西', 'Lionel Messi', '阿根廷', 37, 1),
  createStar(2, '迪马利亚', 'Ángel Di María', '阿根廷', 37, 1),
  createStar(3, '劳塔罗', 'Lautaro Martínez', '阿根廷', 27, 1),
  createStar(4, '恩佐·费尔南德斯', 'Enzo Fernández', '阿根廷', 24, 1),
  createStar(5, '德保罗', 'Rodrigo De Paul', '阿根廷', 30, 1),
  createStar(6, '阿尔瓦雷斯', 'Julián Álvarez', '阿根廷', 25, 1),
  createStar(7, '麦卡利斯特', 'Alexis Mac Allister', '阿根廷', 26, 1),
  createStar(8, '迪巴拉', 'Paulo Dybala', '阿根廷', 31, 1),
  createStar(9, '奥塔门迪', 'Nicolás Otamendi', '阿根廷', 37, 1),
  createStar(10, '罗梅罗', 'Cristian Romero', '阿根廷', 27, 1),
  createStar(11, '阿圭罗', 'Sergio Agüero', '阿根廷', 36, 0),
  createStar(12, '伊瓜因', 'Gonzalo Higuaín', '阿根廷', 37, 0),
  createStar(13, '马斯切拉诺', 'Javier Mascherano', '阿根廷', 40, 0),
  createStar(14, '特维斯', 'Carlos Tévez', '阿根廷', 41, 0),
  createStar(15, '内马尔', 'Neymar', '巴西', 32, 0),
  createStar(16, '维尼修斯', 'Vinícius Júnior', '巴西', 24, 0),
  createStar(17, '阿利松', 'Alisson', '巴西', 32, 0),
  createStar(18, '埃德森', 'Ederson', '巴西', 31, 0),
  createStar(19, '马尔基尼奥斯', 'Marquinhos', '巴西', 30, 0),
  createStar(20, '米利唐', 'Éder Militão', '巴西', 27, 0),
  createStar(21, '卡塞米罗', 'Casemiro', '巴西', 33, 0),
  createStar(22, '罗德里戈', 'Rodrygo', '巴西', 24, 0),
  createStar(23, '拉菲尼亚', 'Raphinha', '巴西', 28, 0),
  createStar(24, '吉马良斯', 'Bruno Guimarães', '巴西', 27, 0),
  createStar(25, '马丁内利', 'Gabriel Martinelli', '巴西', 23, 0),
  createStar(26, '热苏斯', 'Gabriel Jesus', '巴西', 28, 0),
  createStar(27, '理查利森', 'Richarlison', '巴西', 27, 0),
  createStar(28, '菲尔米诺', 'Roberto Firmino', '巴西', 33, 0),
  createStar(29, '马塞洛', 'Marcelo', '巴西', 36, 0),
  createStar(30, '蒂亚戈·席尔瓦', 'Thiago Silva', '巴西', 40, 0),
  createStar(31, '库蒂尼奥', 'Philippe Coutinho', '巴西', 32, 0),
  createStar(32, '威廉', 'Willian', '巴西', 36, 0),
  createStar(33, '苏亚雷斯', 'Luis Suárez', '乌拉圭', 38, 0),
  createStar(34, '巴尔韦德', 'Federico Valverde', '乌拉圭', 26, 0),
  createStar(35, '努涅斯', 'Darwin Núñez', '乌拉圭', 25, 0),
  createStar(36, '戈丁', 'Diego Godín', '乌拉圭', 38, 0),
  createStar(37, '希门尼斯', 'José Giménez', '乌拉圭', 30, 0),
  createStar(38, '阿劳霍', 'Ronald Araújo', '乌拉圭', 26, 0),
  createStar(39, '乌加特', 'Manuel Ugarte', '乌拉圭', 24, 0),
  createStar(40, '卡瓦尼', 'Edinson Cavani', '乌拉圭', 38, 0),
  createStar(41, '弗兰', 'Diego Forlán', '乌拉圭', 45, 0),
  createStar(42, '佩利斯特里', 'Facundo Pellistri', '乌拉圭', 23, 0),
  createStar(43, 'J罗', 'James Rodríguez', '哥伦比亚', 33, 0),
  createStar(44, '路易斯·迪亚斯', 'Luis Díaz', '哥伦比亚', 28, 0),
  createStar(45, '法尔考', 'Radamel Falcao', '哥伦比亚', 39, 0),
  createStar(46, '夸德拉多', 'Juan Cuadrado', '哥伦比亚', 36, 0),
  createStar(47, '奥斯皮纳', 'David Ospina', '哥伦比亚', 36, 0),
  createStar(48, '桑切斯', 'Alexis Sánchez', '智利', 36, 0),
  createStar(49, '比达尔', 'Arturo Vidal', '智利', 37, 0),
  createStar(50, '布拉沃', 'Claudio Bravo', '智利', 42, 0),
  createStar(51, '姆巴佩', 'Kylian Mbappé', '法国', 26, 1),
  createStar(52, '本泽马', 'Karim Benzema', '法国', 37, 0),
  createStar(53, '格列兹曼', 'Antoine Griezmann', '法国', 34, 1),
  createStar(54, '博格巴', 'Paul Pogba', '法国', 32, 1),
  createStar(55, '坎特', "N'Golo Kanté", '法国', 34, 1),
  createStar(56, '特奥', 'Theo Hernández', '法国', 27, 0),
  createStar(57, '迈尼昂', 'Mike Maignan', '法国', 29, 0),
  createStar(58, '乌帕梅卡诺', 'Dayot Upamecano', '法国', 27, 0),
  createStar(59, '科纳特', 'Ibrahima Konaté', '法国', 25, 0),
  createStar(60, '楚阿梅尼', 'Aurélien Tchouaméni', '法国', 25, 0),
  createStar(61, '卡马文加', 'Eduardo Camavinga', '法国', 22, 0),
  createStar(62, '登贝莱', 'Ousmane Dembélé', '法国', 27, 1),
  createStar(63, '吉鲁', 'Olivier Giroud', '法国', 38, 1),
  createStar(64, '瓦拉内', 'Raphaël Varane', '法国', 31, 1),
  createStar(65, '洛里', 'Hugo Lloris', '法国', 38, 1),
  createStar(66, '齐达内', 'Zinedine Zidane', '法国', 52, 1),
  createStar(67, '亨利', 'Thierry Henry', '法国', 47, 1),
  createStar(68, '图拉姆', 'Marcus Thuram', '法国', 27, 0),
  createStar(69, '萨利巴', 'William Saliba', '法国', 24, 0),
  createStar(70, '巴尔科拉', 'Bradley Barcola', '法国', 22, 0),
  createStar(71, '诺伊尔', 'Manuel Neuer', '德国', 39, 1),
  createStar(72, '穆勒', 'Thomas Müller', '德国', 35, 1),
  createStar(73, '穆西亚拉', 'Jamal Musiala', '德国', 22, 0),
  createStar(74, '基米希', 'Joshua Kimmich', '德国', 30, 0),
  createStar(75, '京多安', 'İlkay Gündoğan', '德国', 34, 0),
  createStar(76, '哈弗茨', 'Kai Havertz', '德国', 25, 0),
  createStar(77, '维尔茨', 'Florian Wirtz', '德国', 21, 0),
  createStar(78, '吕迪格', 'Antonio Rüdiger', '德国', 32, 0),
  createStar(79, '特尔施特根', 'Marc-André ter Stegen', '德国', 32, 0),
  createStar(80, '格策', 'Mario Götze', '德国', 32, 1),
  createStar(81, '克罗斯', 'Toni Kroos', '德国', 35, 1),
  createStar(82, '萨内', 'Leroy Sané', '德国', 29, 0),
  createStar(83, '格纳布里', 'Serge Gnabry', '德国', 29, 0),
  createStar(84, '厄齐尔', 'Mesut Özil', '德国', 36, 1),
  createStar(85, '许尔勒', 'André Schürrle', '德国', 34, 1),
  createStar(86, '凯恩', 'Harry Kane', '英格兰', 31, 0),
  createStar(87, '贝林厄姆', 'Jude Bellingham', '英格兰', 21, 0),
  createStar(88, '福登', 'Phil Foden', '英格兰', 24, 0),
  createStar(89, '赖斯', 'Declan Rice', '英格兰', 26, 0),
  createStar(90, '萨卡', 'Bukayo Saka', '英格兰', 23, 0),
  createStar(91, '帕尔默', 'Cole Palmer', '英格兰', 22, 0),
  createStar(92, '斯通斯', 'John Stones', '英格兰', 30, 0),
  createStar(93, '皮克福德', 'Jordan Pickford', '英格兰', 31, 0),
  createStar(94, '阿诺德', 'Trent Alexander-Arnold', '英格兰', 26, 0),
  createStar(95, '格拉利什', 'Jack Grealish', '英格兰', 29, 0),
  createStar(96, '沃特金斯', 'Ollie Watkins', '英格兰', 29, 0),
  createStar(97, '鲁尼', 'Wayne Rooney', '英格兰', 39, 0),
  createStar(98, '杰拉德', 'Steven Gerrard', '英格兰', 44, 0),
  createStar(99, '兰帕德', 'Frank Lampard', '英格兰', 46, 0),
  createStar(100, '贝克汉姆', 'David Beckham', '英格兰', 49, 0),
  createStar(101, '罗德里', 'Rodri', '西班牙', 28, 0),
  createStar(102, '亚马尔', 'Lamine Yamal', '西班牙', 17, 0),
  createStar(103, '佩德里', 'Pedri', '西班牙', 22, 0),
  createStar(104, '加维', 'Gavi', '西班牙', 20, 0),
  createStar(105, '尼科·威廉姆斯', 'Nico Williams', '西班牙', 22, 0),
  createStar(106, '奥尔莫', 'Dani Olmo', '西班牙', 26, 0),
  createStar(107, '卡瓦哈尔', 'Dani Carvajal', '西班牙', 33, 0),
  createStar(108, '拉波尔特', 'Aymeric Laporte', '西班牙', 30, 0),
  createStar(109, '西蒙', 'Unai Simón', '西班牙', 27, 0),
  createStar(110, '莫拉塔', 'Álvaro Morata', '西班牙', 32, 0),
  createStar(111, '伊涅斯塔', 'Andrés Iniesta', '西班牙', 40, 1),
  createStar(112, '哈维', 'Xavi', '西班牙', 45, 1),
  createStar(113, '托雷斯', 'Fernando Torres', '西班牙', 41, 1),
  createStar(114, '布斯克茨', 'Sergio Busquets', '西班牙', 36, 1),
  createStar(115, '拉莫斯', 'Sergio Ramos', '西班牙', 39, 1),
  createStar(116, '库库雷利亚', 'Marc Cucurella', '西班牙', 26, 0),
  createStar(117, '多纳鲁马', 'Gianluigi Donnarumma', '意大利', 26, 0),
  createStar(118, '巴雷拉', 'Nicolò Barella', '意大利', 28, 0),
  createStar(119, '基耶萨', 'Federico Chiesa', '意大利', 27, 0),
  createStar(120, '若日尼奥', 'Jorginho', '意大利', 33, 0),
  createStar(121, '维拉蒂', 'Marco Verratti', '意大利', 32, 0),
  createStar(122, '因西涅', 'Lorenzo Insigne', '意大利', 33, 0),
  createStar(123, '巴斯托尼', 'Alessandro Bastoni', '意大利', 25, 0),
  createStar(124, '迪马尔科', 'Federico Dimarco', '意大利', 27, 0),
  createStar(125, '布冯', 'Gianluigi Buffon', '意大利', 47, 1),
  createStar(126, '皮尔洛', 'Andrea Pirlo', '意大利', 45, 1),
  createStar(127, '托蒂', 'Francesco Totti', '意大利', 48, 1),
  createStar(128, '范戴克', 'Virgil van Dijk', '荷兰', 33, 0),
  createStar(129, '德容', 'Frenkie de Jong', '荷兰', 27, 0),
  createStar(130, '加克波', 'Cody Gakpo', '荷兰', 25, 0),
  createStar(131, '德佩', 'Memphis Depay', '荷兰', 31, 0),
  createStar(132, '邓弗里斯', 'Denzel Dumfries', '荷兰', 28, 0),
  createStar(133, '阿克', 'Nathan Aké', '荷兰', 30, 0),
  createStar(134, '赫拉芬贝赫', 'Ryan Gravenberch', '荷兰', 22, 0),
  createStar(135, '西蒙斯', 'Xavi Simons', '荷兰', 21, 0),
  createStar(136, '罗本', 'Arjen Robben', '荷兰', 41, 0),
  createStar(137, '范佩西', 'Robin van Persie', '荷兰', 41, 0),
  createStar(138, '斯内德', 'Wesley Sneijder', '荷兰', 40, 0),
  createStar(139, 'C罗', 'Cristiano Ronaldo', '葡萄牙', 40, 0),
  createStar(140, 'B费', 'Bruno Fernandes', '葡萄牙', 30, 0),
  createStar(141, '莱奥', 'Rafael Leão', '葡萄牙', 25, 0),
  createStar(142, 'B席', 'Bernardo Silva', '葡萄牙', 30, 0),
  createStar(143, '迪亚斯', 'Rúben Dias', '葡萄牙', 27, 0),
  createStar(144, '门德斯', 'Nuno Mendes', '葡萄牙', 22, 0),
  createStar(145, '帕利尼亚', 'João Palhinha', '葡萄牙', 29, 0),
  createStar(146, '维蒂尼亚', 'Vitinha', '葡萄牙', 25, 0),
  createStar(147, '坎塞洛', 'João Cancelo', '葡萄牙', 30, 0),
  createStar(148, '若塔', 'Diogo Jota', '葡萄牙', 28, 0),
  createStar(149, '菲利克斯', 'João Félix', '葡萄牙', 25, 0),
  createStar(150, '佩佩', 'Pepe', '葡萄牙', 42, 0),
  createStar(151, '德布劳内', 'Kevin De Bruyne', '比利时', 33, 0),
  createStar(152, '卢卡库', 'Romelu Lukaku', '比利时', 31, 0),
  createStar(153, '库尔图瓦', 'Thibaut Courtois', '比利时', 32, 0),
  createStar(154, '多库', 'Jérémy Doku', '比利时', 22, 0),
  createStar(155, '德凯特拉雷', 'Charles De Ketelaere', '比利时', 24, 0),
  createStar(156, '阿扎尔', 'Eden Hazard', '比利时', 34, 0),
  createStar(157, '奥纳纳', 'Amadou Onana', '比利时', 23, 0),
  createStar(158, '莫德里奇', 'Luka Modrić', '克罗地亚', 39, 0),
  createStar(159, '格瓦迪奥尔', 'Joško Gvardiol', '克罗地亚', 23, 0),
  createStar(160, '科瓦契奇', 'Mateo Kovačić', '克罗地亚', 30, 0),
  createStar(161, '佩里西奇', 'Ivan Perišić', '克罗地亚', 36, 0),
  createStar(162, '布罗佐维奇', 'Marcelo Brozović', '克罗地亚', 32, 0),
  createStar(163, '拉基蒂奇', 'Ivan Rakitić', '克罗地亚', 37, 0),
  createStar(164, '莱万多夫斯基', 'Robert Lewandowski', '波兰', 36, 0),
  createStar(165, '哈兰德', 'Erling Haaland', '挪威', 24, 0),
  createStar(166, '厄德高', 'Martin Ødegaard', '挪威', 26, 0),
  createStar(167, '扎卡', 'Granit Xhaka', '瑞士', 32, 0),
  createStar(168, '索默', 'Yann Sommer', '瑞士', 36, 0),
  createStar(169, '伊萨克', 'Alexander Isak', '瑞典', 25, 0),
  createStar(170, '米特罗维奇', 'Aleksandar Mitrović', '塞尔维亚', 30, 0),
  createStar(171, '弗拉霍维奇', 'Dušan Vlahović', '塞尔维亚', 25, 0),
  createStar(172, '津琴科', 'Oleksandr Zinchenko', '乌克兰', 28, 0),
  createStar(173, '多夫比克', 'Artem Dovbyk', '乌克兰', 27, 0),
  createStar(174, '霍伊伦德', 'Rasmus Højlund', '丹麦', 22, 0),
  createStar(175, '埃里克森', 'Christian Eriksen', '丹麦', 33, 0),
  createStar(176, '索博斯洛伊', 'Dominik Szoboszlai', '匈牙利', 24, 0),
  createStar(177, '恰尔汗奥卢', 'Hakan Çalhanoğlu', '土耳其', 31, 0),
  createStar(178, '居莱尔', 'Arda Güler', '土耳其', 20, 0),
  createStar(179, '科瓦拉茨赫利亚', 'Khvicha Kvaratskhelia', '格鲁吉亚', 24, 0),
  createStar(180, '什克里尼亚尔', 'Milan Škriniar', '斯洛伐克', 30, 0),
  createStar(181, '奥布拉克', 'Jan Oblak', '斯洛文尼亚', 32, 0),
  createStar(182, '舍甫琴科', 'Andriy Shevchenko', '乌克兰', 48, 0),
  createStar(183, '萨拉赫', 'Mohamed Salah', '埃及', 32, 0),
  createStar(184, '马内', 'Sadio Mané', '塞内加尔', 32, 0),
  createStar(185, '奥斯梅恩', 'Victor Osimhen', '尼日利亚', 26, 0),
  createStar(186, '阿什拉夫', 'Achraf Hakimi', '摩洛哥', 26, 0),
  createStar(187, '恩内斯里', 'Youssef En-Nesyri', '摩洛哥', 27, 0),
  createStar(188, '齐耶赫', 'Hakim Ziyech', '摩洛哥', 32, 0),
  createStar(189, '博尼费斯', 'Victor Boniface', '尼日利亚', 24, 0),
  createStar(190, '奥纳纳', 'André Onana', '喀麦隆', 28, 0),
  createStar(191, '托马斯', 'Thomas Partey', '加纳', 31, 0),
  createStar(192, '库杜斯', 'Mohammed Kudus', '加纳', 24, 0),
  createStar(193, '马赫雷斯', 'Riyad Mahrez', '阿尔及利亚', 34, 0),
  createStar(194, '阿莱', 'Sébastien Haller', '科特迪瓦', 30, 0),
  createStar(195, '德罗巴', 'Didier Drogba', '科特迪瓦', 47, 0),
  createStar(196, '埃托奥', 'Samuel Eto\'o', '喀麦隆', 44, 0),
  createStar(197, '亚亚图雷', 'Yaya Touré', '科特迪瓦', 41, 0),
  createStar(198, '门迪', 'Édouard Mendy', '塞内加尔', 33, 0),
  createStar(199, '孙兴慜', 'Son Heung-min', '韩国', 32, 0),
  createStar(200, '金玟哉', 'Kim Min-jae', '韩国', 28, 0),
  createStar(201, '久保建英', 'Takefusa Kubo', '日本', 23, 0),
  createStar(202, '三笘薰', 'Kaoru Mitoma', '日本', 27, 0),
  createStar(203, '远藤航', 'Wataru Endo', '日本', 32, 0),
  createStar(204, '南野拓実', 'Takumi Minamino', '日本', 30, 0),
  createStar(205, '伊东纯也', 'Junya Ito', '日本', 32, 0),
  createStar(206, '李刚仁', 'Lee Kang-in', '韩国', 24, 0),
  createStar(207, '黄喜灿', 'Hwang Hee-chan', '韩国', 29, 0),
  createStar(208, '塔雷米', 'Mehdi Taremi', '伊朗', 32, 0),
  createStar(209, '阿兹蒙', 'Sardar Azmoun', '伊朗', 30, 0),
  createStar(210, '古德温', 'Craig Goodwin', '澳大利亚', 33, 0),
  createStar(211, '阿菲夫', 'Akram Afif', '卡塔尔', 29, 0),
  createStar(212, '阿方索·戴维斯', 'Alphonso Davies', '加拿大', 24, 0),
  createStar(213, '大卫', 'Jonathan David', '加拿大', 25, 0),
  createStar(214, '普利西奇', 'Christian Pulišić', '美国', 26, 0),
  createStar(215, '麦肯尼', 'Weston McKennie', '美国', 25, 0),
  createStar(216, '雷纳', 'Giovanni Reyna', '美国', 22, 0),
  createStar(217, '洛萨诺', 'Hirving Lozano', '墨西哥', 29, 0),
  createStar(218, '奥乔亚', 'Guillermo Ochoa', '墨西哥', 39, 0),
  createStar(219, '纳瓦斯', 'Keylor Navas', '哥斯达黎加', 38, 0),
  createStar(220, '贝利', 'Leon Bailey', '牙买加', 27, 0)
];

function normalizeText(text) {
  return text.trim().toLowerCase();
}

function searchStars(keyword, excludeIds = []) {
  const kw = normalizeText(keyword);
  if (!kw) return [];
  return stars.filter(star => {
    if (excludeIds.includes(star.id)) return false;
    return (
      normalizeText(star.name).includes(kw) ||
      normalizeText(star.nameEn).includes(kw) ||
      normalizeText(star.country).includes(kw)
    );
  }).slice(0, 10);
}

function getRandomTargetStar() {
  const index = Math.floor(Math.random() * stars.length);
  const star = stars[index];
  return { ...star };
}

window.stars = stars;
window.getWorldCupWins = getWorldCupWins;
window.getContinent = getContinent;
window.calculateAge = calculateAge;
window.searchStars = searchStars;
window.getRandomTargetStar = getRandomTargetStar;
